### ISSUE TITLE
Broken with AS 3

### ISSUE THREAD

**Issue by ltpquang** [sergiiz/RxBasicsKata#12]
I had downloaded and tried this repo before, all worked fine. Recently I download the repo again but it doesn't anymore. The problem seems to be related to Android Studio and IntelliJ. Anyone have workarounds?

```
Class not found: "org.sergiiz.rxkata.CountriesServiceSolvedTest"Empty test suite.
```

**Comment by sergiiz** [comment]
Thanks for reporting! yes something doesn't work,I'll check it

**Comment by sergiiz** [comment]
Fixed, thanks! Android dependencies removed to make project simpler. You'll need to use console or intellij to run tests now.

**Comment by CoolMind** [comment]
In AS 3.1 when run first test, I receive:

> Process finished with exit code 1
> Class not found: "CountriesServiceSolvedTest"Empty test suite.
