### ISSUE TITLE
Flattening the gradle multi-project?

### ISSUE THREAD

**Issue by Petikoch** [sergiiz/RxBasicsKata#3]
Hi Segii,

thanks for the nice articel and the kata, I really enjoyed it.

Is there any reason why you did a gradle multi-project? A simple gradle project would be enough and simpler...

Best regards,
Peti

**Comment by sergiiz** [comment]
Thanks for this idea @Petikoch, I'll check if it works good with all IDEs

**Comment by sergiiz** [comment]
Finally fixed :)
together with #12
