### ISSUE TITLE
Cloning the project — can't see a module directory

### ISSUE THREAD

**Issue by AlexSheiko** [sergiiz/RxBasicsKata#8]
Hello, Sergii.

1. I've copied the repository link
2. Inserted it to Android Studio → Project from VC → GitHub
3. And imported it without errors. But:

**Problem**
I can't see the `rxkata` module, which contains code and tests. I'm using both [Project](https://d.pr/x6jT) and [Android](https://d.pr/5RUl) perspective in the Project View.

**Note**
It's probably just a lack of knowledge about Gradle on my side, but I'd be grateful it you can help. Perhaps a few other people are also searching for the solution.

And in any case, thank you for creating this project.

**Comment by ritesh-singh** [comment]
It's probably because you might be trying to import it as Android Project.
I have imported it on IntelliJ, as a gradle project and it's working fine.

**Comment by AlexSheiko** [comment]
Thank you, @ritesh-singh!

I was able to run the project. For anyone interested:

1. Disable `Android Support` plugin in File → Settings → Plugins
2. Import the project
3. Do not re-enable Android plugin while you're using the project

Alternatively, we can [modify](http://stackoverflow.com/a/31247640/4561041) the project to open with Android plugin. I haven't tried that yet.
